Use release-downloader action with retries to download CLI binary from GH release in generated GHA workflow

diff --git a/test/cli/project-init/ok-interactive/out/.github/actions/install/action.yml b/test/cli/project-init/ok-interactive/out/.github/actions/install/action.yml
--- a/test/cli/project-init/ok-interactive/out/.github/actions/install/action.yml
+++ b/test/cli/project-init/ok-interactive/out/.github/actions/install/action.yml
@@ -1,28 +1,36 @@
 name: Keboola as Code Install
 description: Install Keboola as Code CLI
+inputs:
+  githubToken:
+    description: GitHub Workflow Token
+    required: true
 runs:
   using: "composite"
   steps:
-    # Set releases URL
-    - id: kbc_releases_url
+    - id: prepare
       run: |
-        url='https://api.github.com/repos/keboola/keboola-as-code/releases?per_page=5'
-        echo "KBC_RELEASES_URL=$url" >> $GITHUB_ENV
-        echo "Releases URL: $url"
+        mkdir "${{ runner.temp }}/kbc"
       shell: bash
-    # Get URL of the latest release asset
-    - id: kbc_latest_release_url
+    # Download the latest release asset
+    - id: kbc_download_latest_release
+      uses: robinraju/release-downloader@v1.7
+      with:
+        repository: "keboola/keboola-as-code"
+        latest: true
+        fileName: "*_linux_amd64.zip"
+        token: ${{ inputs.githubToken }}
+        out-file-path: "${{ runner.temp }}/kbc"
+    # Extract binary
+    - id: kbc_extract_release
       run: |
-        url=`curl -sL $KBC_RELEASES_URL | jq -r '[.[].assets[] | select(.name | contains("linux_amd64.zip"))] | first.browser_download_url'`
-        echo "KBC_RELEASE_URL=$url" >> $GITHUB_ENV
-        echo "Latest release URL: $url"
-      shell: bash
-    # Download and extract binary
-    - id: kbc_download_and_extract_release
-      run: |
-        release_zip="$RUNNER_TEMP/release.zip"
+        latest_tag=${{steps.kbc_download_latest_release.outputs.tag_name}}
+        latest_version=${latest_tag:1}
+        release_zip="${{ runner.temp }}/kbc/keboola-cli_${latest_version}_linux_amd64.zip"
+        if [ ! -f "$release_zip" ]; then
+          echo "Could not download keboola-cli_${latest_version}_linux_amd64.zip from the latest release."
+          exit 1
+        fi
         release_bin="/usr/local/bin/kbc"
-        curl -sSLo "$release_zip" "$KBC_RELEASE_URL"
         unzip "$release_zip" -d /usr/local/bin
         chmod +x "$release_bin"
         echo "Keboola as Code CLI installed: $release_bin"
