fix: Wrong fix of linting

diff --git a/.github/workflows/test-k8s-service-apps-proxy.yml b/.github/workflows/test-k8s-service-apps-proxy.yml
--- a/.github/workflows/test-k8s-service-apps-proxy.yml
+++ b/.github/workflows/test-k8s-service-apps-proxy.yml
@@ -5,10 +5,6 @@ on:
   # This workflow is also part of the release pipeline,
   # in that case, the actual version is deployed twice.
   workflow_call:
-    inputs:
-      version:
-        type: string
-        required: false
   # In PR the previous version is deployed first and then the actual version.
   pull_request:
     paths:
@@ -117,7 +113,7 @@ jobs:
           --labels="app=datadog-agent" \
           --env="POD_IP=$POD_IP" \
           --env="METRICS_PORT=$METRICS_PORT" \
-          --command -- sh -c "set -eo pipefail; curl -f -L --max-time 5 \"$POD_IP:$METRICS_PORT/metrics\" | tail"
+          --command -- sh -c "set -eo pipefail; curl -f -L --max-time 5 "$POD_IP:$METRICS_PORT/metrics" | tail"
 
       - name: Check forbidden access to the API metrics from other places
         if: always()
@@ -129,12 +125,12 @@ jobs:
             --image docker.io/alpine/curl \
             --env="POD_IP=$POD_IP" \
             --env="METRICS_PORT=$METRICS_PORT" \
-            --command -- sh -c "set -eo pipefail; curl -f -L --max-time 5 \"$POD_IP:$METRICS_PORT/metrics\" | tail"; then
-          echo "The command did not fail, but it should have."
-          exit 1
+            --command -- sh -c "set -eo pipefail; curl -f -L --max-time 5 "$POD_IP:$METRICS_PORT/metrics" | tail"; then
+            echo "The command did not fail, but it should have."
+            exit 1
           else
-          echo "The command failed, OK."
-          exit 0
+            echo "The command failed, OK."
+            exit 0
           fi
 
       - name: Check Proxy response
@@ -148,15 +144,15 @@ jobs:
 
           # Diff JSON states
           /tmp/latest-scripts/k8s/diff.sh \
-          /tmp/artifacts/test-k8s-state.old.json \
-          /tmp/artifacts/test-k8s-state.new.json \
-          /tmp/artifacts/test-k8s-state.diff || true
+            /tmp/artifacts/test-k8s-state.old.json \
+            /tmp/artifacts/test-k8s-state.new.json \
+            /tmp/artifacts/test-k8s-state.diff || true
 
           # Remove ANSI sequences
           sed -e 's/\x1b\[[0-9;]*m//g' -i /tmp/artifacts/test-k8s-state.diff || true
 
           # Prepare PR comment message
-          echo -e "  ##  # ${{ env.SERVICE_NAME }} Kubernetes Diff [CI]\n\n" >> /tmp/artifacts/test-k8s-state.diff.message
+          echo -e "### ${{ env.SERVICE_NAME }} Kubernetes Diff [CI]\n\n" >> /tmp/artifacts/test-k8s-state.diff.message
           echo -e "Between \`base\` ${{ github.event.pull_request.base.sha }} :arrow_left:  \`head\` ${{ github.event.pull_request.head.sha }}.\n\n" >> /tmp/artifacts/test-k8s-state.diff.message
           echo -e "<details>\n<summary>Expand</summary>\n\n\`\`\`diff\n" >> /tmp/artifacts/test-k8s-state.diff.message
           head -c 50000 /tmp/artifacts/test-k8s-state.diff >> /tmp/artifacts/test-k8s-state.diff.message || true
@@ -177,7 +173,6 @@ jobs:
           if-no-files-found: error
 
       - name: Send PR comment
-        if: always()
         uses: marocchino/sticky-pull-request-comment@v2
         with:
           header: "${{ env.KUBERNETES_NAMESPACE }}-kubernetes-state-diff"
diff --git a/.github/workflows/test-k8s-service-stream.yml b/.github/workflows/test-k8s-service-stream.yml
--- a/.github/workflows/test-k8s-service-stream.yml
+++ b/.github/workflows/test-k8s-service-stream.yml
@@ -5,10 +5,6 @@ on:
   # This workflow is also part of the release pipeline,
   # in that case, the actual version is deployed twice.
   workflow_call:
-    inputs:
-      version:
-        type: string
-        required: false
   # In PR the previous version is deployed first and then the actual version.
   pull_request:
     paths:
@@ -23,18 +19,13 @@ env:
   MINIKUBE_DRIVER: docker
 
   KUBERNETES_NAMESPACE: stream
-  KUBERNETES_ROLLOUT_WAIT: 300s
+  KUBERNETES_ROLLOUT_WAIT: 200s
   REMOVE_RESOURCES_LIMITS: true
 
   SERVICE_NAME: Stream
-  API_RELEASE_NAME: stream-api
-  COLLECTOR_RELEASE_NAME: stream-collector
+  ETCD_RELEASE_NAME: stream-etcd
+  ETCD_ENDPOINT: stream-etcd-headless.stream.svc.cluster.local:2379
   METRICS_PORT: 9000
-
-  STORAGE_API_RELEASE_NAME: stream-storage-api
-  STORAGE_COORDINATOR_RELEASE_NAME: stream-storage-coordinator
-  STORAGE_WRITER_RELEASE_NAME: stream-storage-writer
-  STORAGE_READER_RELEASE_NAME: stream-storage-reader
 
 defaults:
   run:
@@ -42,13 +33,23 @@ defaults:
 
 jobs:
   test:
-    name: "K8S test: Stream"
+    name: "K8S test: Stream Service"
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
         with:
           ref: ${{ github.event.pull_request.head.ref }}
+
+      - name: Free Disk Space (Ubuntu)
+        uses: jlumbroso/free-disk-space@main
+        with:
+          android: true
+          dotnet: true
+          haskell: true
+          large-packages: false
+          docker-images: false
+          swap-storage: false
 
       - name: Create artifacts directory
         run: mkdir -p /tmp/artifacts
@@ -106,123 +107,160 @@ jobs:
           # Dump objects
           /tmp/latest-scripts/k8s/dump.sh /tmp/artifacts/test-k8s-state.new.json
 
+      - name: Check deployment of the etcd
+        if: always()
+        run: kubectl rollout status "sts/$ETCD_RELEASE_NAME" --timeout=10s
+
       - name: Check deployment of the API nodes
         if: always()
-        run: kubectl rollout status "deployment/$API_RELEASE_NAME" --timeout=10s
+        run: kubectl rollout status "deployment/stream-api" --timeout=10s
 
-      - name: Check deployment of the Collector nodes
+      - name: Check deployment of the HTTP source nodes
         if: always()
-        run: kubectl rollout status "deployment/$COLLECTOR_RELEASE_NAME" --timeout=10s
+        run: kubectl rollout status "deployment/stream-http-source" --timeout=10s
 
-      - name: Check deployment of the Storage API nodes
+      - name: Check deployment of the storage writer/reader nodes
         if: always()
-        run: kubectl rollout status "deployment/$STORAGE_API_RELEASE_NAME" --timeout=10s
+        run: kubectl rollout status "sts/stream-storage-writer-reader" --timeout=10s
 
-      - name: Check deployment of the Storage Coordinator nodes
+      - name: Check deployment of the storage coordinator nodes
         if: always()
-        run: kubectl rollout status "deployment/$STORAGE_COORDINATOR_RELEASE_NAME" --timeout=30s
+        run: kubectl rollout status "deployment/stream-storage-coordinator" --timeout=10s
 
-      - name: Check deployment of the Storage Writer nodes
-        if: always()
-        run: kubectl rollout status "statefulset/$STORAGE_WRITER_RELEASE_NAME" --timeout=10s
-
-      - name: Check deployment of the Storage Reader nodes
-        if: always()
-        run: kubectl rollout status "statefulset/$STORAGE_READER_RELEASE_NAME" --timeout=10s
-
-      - name: Check access to API metrics from the DataDog Agent
+      - name: Check access to the metrics from the DataDog Agent
         if: always()
         run: |
           set -Eeuo pipefail
           kubectl create namespace datadog || true
-          export POD_IP=`kubectl get pod -l app=stream-api -o=jsonpath='{.items[0].status.podIP}'`
-          echo "Pod IP: $POD_IP"
-          kubectl run --attach --rm --restart=Never check-api-datadog \
-          --namespace datadog \
-          --image docker.io/alpine/curl \
-          --labels="app=datadog-agent" \
-          --env="POD_IP=$POD_IP" \
-          --env="METRICS_PORT=$METRICS_PORT" \
-          --command -- sh -c "set -eo pipefail; curl -f -L --max-time 5 \"$POD_IP:$METRICS_PORT/metrics\" | tail"
 
-      - name: Check forbidden access to the API metrics from other places
+          for APP_WITH_METRICS_PORT in "stream-api:9000" "stream-http-source:9000" "stream-storage-writer-reader:9001" "stream-storage-writer-reader:9002" "stream-storage-coordinator:9000"
+          do
+            IFS=: read -r APP METRICS_PORT <<< "$APP_WITH_METRICS_PORT"
+            echo "---------------------------------"
+            echo "Checking $APP:$METRICS_PORT"
+            export POD_IP=`kubectl get pod -l "app=$APP" -o=jsonpath='{.items[0].status.podIP}'`
+            echo "Pod IP: $POD_IP"
+            kubectl run --attach --rm --restart=Never check-api-datadog \
+            --namespace datadog \
+            --image docker.io/alpine/curl \
+            --labels="app=datadog-agent" \
+            --env="POD_IP=$POD_IP" \
+            --env="METRICS_PORT=$METRICS_PORT" \
+            --command -- sh -c "set -eo pipefail; curl -f -L --max-time 5 \"$POD_IP:$METRICS_PORT/metrics\" | tail"
+            echo "---------------------------------"
+          done
+
+      - name: Check forbidden access to the metrics from other places
         if: always()
         run: |
           set -Eeuo pipefail
-          export POD_IP=`kubectl get pod -l app=stream-api -o=jsonpath='{.items[0].status.podIP}'`
-          echo "Pod IP: $POD_IP"
-          if kubectl run --attach --rm --restart=Never check-api-other \
-            --image docker.io/alpine/curl \
-            --env="POD_IP=$POD_IP" \
-            --env="METRICS_PORT=$METRICS_PORT" \
-            --command -- sh -c "set -eo pipefail; curl -f -L --max-time 5 \"$POD_IP:$METRICS_PORT/metrics\" | tail"; then
-          echo "The command did not fail, but it should have."
-          exit 1
-          else
-          echo "The command failed, OK."
-          exit 0
-          fi
 
-      - name: Check access to Storage API metrics from the DataDog Agent
+          for APP_WITH_METRICS_PORT in "stream-api:9000" "stream-http-source:9000" "stream-storage-writer-reader:9001" "stream-storage-writer-reader:9002" "stream-storage-coordinator:9000"
+          do
+            IFS=: read -r APP METRICS_PORT <<< "$APP_WITH_METRICS_PORT"
+            echo "---------------------------------"
+            echo "Checking $APP:$METRICS_PORT"
+            export POD_IP=`kubectl get pod -l "app=$APP" -o=jsonpath='{.items[0].status.podIP}'`
+            echo "Pod IP: $POD_IP"
+            if kubectl run --attach --rm --restart=Never check-api-other \
+              --image docker.io/alpine/curl \
+              --env="POD_IP=$POD_IP" \
+              --env="METRICS_PORT=$METRICS_PORT" \
+              --command -- sh -c "set -eo pipefail; curl -f -L --max-time 5 \"$POD_IP:$METRICS_PORT/metrics\" | tail"; then
+              echo "The command did not fail, but it should have."
+              exit 1
+            else
+              echo "The command failed, OK."
+              exit 0
+            fi
+            echo "---------------------------------"
+          done
+
+      - name: Check access to the etcd from a client
+        if: always()
+        run: |
+          set -Eeuo pipefail
+          export ETCD_ROOT_PASSWORD=$(kubectl get secret "$ETCD_RELEASE_NAME" -o jsonpath="{.data.etcd-root-password}" 2>/dev/null | base64 -d)
+          kubectl run --attach --rm --restart=Never check-etcd-client \
+            --image docker.io/bitnami/etcd \
+            --labels="${ETCD_RELEASE_NAME}-client=true" \
+            --env="ETCD_ROOT_PASSWORD=$ETCD_ROOT_PASSWORD" \
+            --env="ETCDCTL_ENDPOINTS=$ETCD_ENDPOINT" \
+            --command -- etcdctl --dial-timeout=10s --user root:$ETCD_ROOT_PASSWORD put /message Hello
+
+      - name: Check access to the etcd from the DataDog Agent
         if: always()
         run: |
           set -Eeuo pipefail
           kubectl create namespace datadog || true
-          export POD_IP=`kubectl get pod -l app=stream-storage-api -o=jsonpath='{.items[0].status.podIP}'`
-          echo "Pod IP: $POD_IP"
-          kubectl run --attach --rm --restart=Never check-storage-api-datadog \
+          kubectl run --attach --rm --restart=Never check-etcd-other-datadog \
           --namespace datadog \
           --image docker.io/alpine/curl \
           --labels="app=datadog-agent" \
-          --env="POD_IP=$POD_IP" \
-          --env="METRICS_PORT=$METRICS_PORT" \
-          --command -- sh -c "set -eo pipefail; curl -f -L --max-time 5 \"$POD_IP:$METRICS_PORT/metrics\" | tail"
+          --env="ETCD_ENDPOINT=$ETCD_ENDPOINT" \
+          --command -- sh -c "set -eo pipefail; curl -f -L --max-time 5 "$ETCD_ENDPOINT/metrics" | tail"
 
-      - name: Check forbidden access to the Storage API metrics from other places
+      - name: Check forbidden access to the etcd from other places
         if: always()
         run: |
           set -Eeuo pipefail
-          export POD_IP=`kubectl get pod -l app=stream-storage-api -o=jsonpath='{.items[0].status.podIP}'`
-          echo "Pod IP: $POD_IP"
-          if kubectl run --attach --rm --restart=Never check-storage-api-other \
+          if kubectl run --attach --rm --restart=Never check-etcd-other \
             --image docker.io/alpine/curl \
-            --env="POD_IP=$POD_IP" \
-            --env="METRICS_PORT=$METRICS_PORT" \
-            --command -- sh -c "set -eo pipefail; curl -f -L --max-time 5 \"$POD_IP:$METRICS_PORT/metrics\" | tail"; then
-          echo "The command did not fail, but it should have."
-          exit 1
+            --env="ETCD_ENDPOINT=$ETCD_ENDPOINT" \
+            --command -- sh -c "set -eo pipefail; curl -f -L --max-time 5 "$ETCD_ENDPOINT/metrics" | tail"; then
+            echo "The command did not fail, but it should have."
+            exit 1
           else
-          echo "The command failed, OK."
-          exit 0
+            echo "The command failed, OK."
+            exit 0
           fi
 
-      - name: Check Stream API response
+      - name: Check API response
         if: always()
-        run: curl --fail -L -s --max-time 5 "$(minikube service --url $API_RELEASE_NAME --namespace $KUBERNETES_NAMESPACE)/health-check"
+        run: |
+          hostPort=$(minikube service --url stream-api --namespace $KUBERNETES_NAMESPACE)
+          echo "$hostPort"
+          curl --fail -s --max-time 5 --retry 5 --retry-connrefused "$hostPort/health-check"
 
-      - name: Check Storage API response
+      - name: Check HTTP source response
         if: always()
-        run: curl --fail -L -s --max-time 5 "$(minikube service --url $STORAGE_API_RELEASE_NAME --namespace $KUBERNETES_NAMESPACE)/health-check"
+        run: |
+          hostPort=$(minikube service --url stream-http-source --namespace $KUBERNETES_NAMESPACE)
+          curl --fail -s --max-time 5 --retry 5 --retry-connrefused "$hostPort/health-check"
+
+      - name: Test etcd defragmentation cron job
+        if: always()
+        run: |
+          set -Eeuo pipefail
+          # Create a job from the cron job
+          kubectl create job "--from=cronjob/${ETCD_RELEASE_NAME}-defrag" test-defrag-job
+          # Wait for the job
+          if kubectl wait --for=condition=complete --timeout=30s job/test-defrag-job; then
+            echo "The job succeed, logs:"
+            kubectl logs --selector="job-name=test-defrag-job"
+            exit 0
+          else
+            echo "The job failed, logs:"
+            kubectl logs --selector="job-name=test-defrag-job"
+            exit 1
+          fi
 
       - name: Diff the old and the new Kubernetes state
         if: always()
         run: |
           set -Eeuo pipefail
-
           # Diff JSON states
           /tmp/latest-scripts/k8s/diff.sh \
-          /tmp/artifacts/test-k8s-state.old.json \
-          /tmp/artifacts/test-k8s-state.new.json \
-          /tmp/artifacts/test-k8s-state.diff || true
-
+            /tmp/artifacts/test-k8s-state.old.json \
+            /tmp/artifacts/test-k8s-state.new.json \
+            /tmp/artifacts/test-k8s-state.diff
           # Remove ANSI sequences
           sed -e 's/\x1b\[[0-9;]*m//g' -i /tmp/artifacts/test-k8s-state.diff || true
-
           # Prepare PR comment message
-          echo -e "  ##  # ${{ env.SERVICE_NAME }} Kubernetes Diff [CI]\n\n" >> /tmp/artifacts/test-k8s-state.diff.message
+          echo -e "### ${{ env.SERVICE_NAME }} Kubernetes Diff [CI]\n\n" >> /tmp/artifacts/test-k8s-state.diff.message
           echo -e "Between \`base\` ${{ github.event.pull_request.base.sha }} :arrow_left:  \`head\` ${{ github.event.pull_request.head.sha }}.\n\n" >> /tmp/artifacts/test-k8s-state.diff.message
           echo -e "<details>\n<summary>Expand</summary>\n\n\`\`\`diff\n" >> /tmp/artifacts/test-k8s-state.diff.message
-          head -c 50000 /tmp/artifacts/test-k8s-state.diff >> /tmp/artifacts/test-k8s-state.diff.message || true
+          head -c 50000 /tmp/artifacts/test-k8s-state.diff >> /tmp/artifacts/test-k8s-state.diff.message
           echo -e "\n\n(see artifacts in the Github Action for more information)\n\`\`\`\n</details>" >> /tmp/artifacts/test-k8s-state.diff.message
 
       - name: Dump logs
@@ -240,7 +278,6 @@ jobs:
           if-no-files-found: error
 
       - name: Send PR comment
-        if: always()
         uses: marocchino/sticky-pull-request-comment@v2
         with:
           header: "${{ env.KUBERNETES_NAMESPACE }}-kubernetes-state-diff"
diff --git a/.github/workflows/test-k8s-service-templates.yml b/.github/workflows/test-k8s-service-templates.yml
--- a/.github/workflows/test-k8s-service-templates.yml
+++ b/.github/workflows/test-k8s-service-templates.yml
@@ -5,10 +5,6 @@ on:
   # This workflow is also part of the release pipeline,
   # in that case, the actual version is deployed twice.
   workflow_call:
-    inputs:
-      version:
-        type: string
-        required: false
   # In PR the previous version is deployed first and then the actual version.
   pull_request:
     paths:
@@ -16,18 +12,20 @@ on:
       - provisioning/templates-api/**
       - provisioning/common/**
       # When the config structure is changed it may be necessary to adjust k8s configmap.
-      - internal/pkg/service/templates/config/**
+      - internal/pkg/service/templates/api/config/**
 
 env:
-  MINIKUBE_PROFILE: templates
+  MINIKUBE_PROFILE: templates-api
   MINIKUBE_DRIVER: docker
 
-  KUBERNETES_NAMESPACE: templates
+  KUBERNETES_NAMESPACE: templates-api
   KUBERNETES_ROLLOUT_WAIT: 200s
   REMOVE_RESOURCES_LIMITS: true
 
-  SERVICE_NAME: Templates
+  SERVICE_NAME: Templates API
   API_RELEASE_NAME: templates-api
+  ETCD_RELEASE_NAME: templates-api-etcd
+  ETCD_ENDPOINT: templates-api-etcd-headless.templates-api.svc.cluster.local:2379
   METRICS_PORT: 9000
 
 defaults:
@@ -36,7 +34,7 @@ defaults:
 
 jobs:
   test:
-    name: "K8S test: Templates"
+    name: "K8S test: Templates Service"
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -95,10 +93,15 @@ jobs:
           echo "$emptyReplicaSets"
           echo "-------------------------"
           echo "$emptyReplicaSets" | xargs --no-run-if-empty -I {} kubectl delete replicaset "{}"
+
           # Wait for pod startup/termination
           sleep 10
           # Dump objects
           /tmp/latest-scripts/k8s/dump.sh /tmp/artifacts/test-k8s-state.new.json
+
+      - name: Check deployment of the etcd
+        if: always()
+        run: kubectl rollout status "sts/$ETCD_RELEASE_NAME" --timeout=10s
 
       - name: Check deployment of the API nodes
         if: always()
@@ -117,7 +120,7 @@ jobs:
           --labels="app=datadog-agent" \
           --env="POD_IP=$POD_IP" \
           --env="METRICS_PORT=$METRICS_PORT" \
-          --command -- sh -c "set -eo pipefail; curl -f -L --max-time 5 \"$POD_IP:$METRICS_PORT/metrics\" | tail"
+          --command -- sh -c "set -eo pipefail; curl -f -L --max-time 5 "$POD_IP:$METRICS_PORT/metrics" | tail"
 
       - name: Check forbidden access to the API metrics from other places
         if: always()
@@ -129,37 +132,90 @@ jobs:
             --image docker.io/alpine/curl \
             --env="POD_IP=$POD_IP" \
             --env="METRICS_PORT=$METRICS_PORT" \
-            --command -- sh -c "set -eo pipefail; curl -f -L --max-time 5 \"$POD_IP:$METRICS_PORT/metrics\" | tail"; then
-          echo "The command did not fail, but it should have."
-          exit 1
+            --command -- sh -c "set -eo pipefail; curl -f -L --max-time 5 "$POD_IP:$METRICS_PORT/metrics" | tail"; then
+            echo "The command did not fail, but it should have."
+            exit 1
           else
-          echo "The command failed, OK."
-          exit 0
+            echo "The command failed, OK."
+            exit 0
           fi
 
-      - name: Check Templates API response
+      - name: Check access to the etcd from a client
         if: always()
-        run: curl --fail -L -s --max-time 5 "$(minikube service --url $API_RELEASE_NAME --namespace $KUBERNETES_NAMESPACE)/health-check"
+        run: |
+          set -Eeuo pipefail
+          export ETCD_ROOT_PASSWORD=$(kubectl get secret "$ETCD_RELEASE_NAME" -o jsonpath="{.data.etcd-root-password}" 2>/dev/null | base64 -d)
+          kubectl run --attach --rm --restart=Never check-etcd-client \
+            --image docker.io/bitnami/etcd \
+            --labels="${ETCD_RELEASE_NAME}-client=true" \
+            --env="ETCD_ROOT_PASSWORD=$ETCD_ROOT_PASSWORD" \
+            --env="ETCDCTL_ENDPOINTS=$ETCD_ENDPOINT" \
+            --command -- etcdctl --dial-timeout=10s --user root:$ETCD_ROOT_PASSWORD put /message Hello
+
+      - name: Check access to the etcd from the DataDog Agent
+        if: always()
+        run: |
+          set -Eeuo pipefail
+          kubectl create namespace datadog || true
+          kubectl run --attach --rm --restart=Never check-etcd-other-data-dog \
+          --namespace datadog \
+          --image docker.io/alpine/curl \
+          --labels="app=datadog-agent" \
+          --env="ETCD_ENDPOINT=$ETCD_ENDPOINT" \
+          --command -- sh -c "set -eo pipefail; curl -f -L --max-time 5 "$ETCD_ENDPOINT/metrics" | tail"
+
+      - name: Check forbidden access to the etcd from other places
+        if: always()
+        run: |
+          set -Eeuo pipefail
+          if kubectl run --attach --rm --restart=Never check-etcd-other \
+            --image docker.io/alpine/curl \
+            --env="ETCD_ENDPOINT=$ETCD_ENDPOINT" \
+            --command -- sh -c "set -eo pipefail; curl -f -L --max-time 5 "$ETCD_ENDPOINT/metrics" | tail"; then
+            echo "The command did not fail, but it should have."
+            exit 1
+          else
+            echo "The command failed, OK."
+            exit 0
+          fi
+
+      - name: Check API response
+        if: always()
+        run: curl --fail -L -s --max-time 5 "$(minikube service --url $API_RELEASE_NAME --namespace $KUBERNETES_NAMESPACE)"
+
+      - name: Test etcd defragmentation cron job
+        if: always()
+        run: |
+          set -Eeuo pipefail
+          # Create a job from the cron job
+          kubectl create job "--from=cronjob/${ETCD_RELEASE_NAME}-defrag" test-defrag-job
+          # Wait for the job
+          if kubectl wait --for=condition=complete --timeout=30s job/test-defrag-job; then
+            echo "The job succeed, logs:"
+            kubectl logs --selector="job-name=test-defrag-job"
+            exit 0
+          else
+            echo "The job failed, logs:"
+            kubectl logs --selector="job-name=test-defrag-job"
+            exit 1
+          fi
 
       - name: Diff the old and the new Kubernetes state
         if: always()
         run: |
           set -Eeuo pipefail
-
           # Diff JSON states
           /tmp/latest-scripts/k8s/diff.sh \
-          /tmp/artifacts/test-k8s-state.old.json \
-          /tmp/artifacts/test-k8s-state.new.json \
-          /tmp/artifacts/test-k8s-state.diff || true
-
+            /tmp/artifacts/test-k8s-state.old.json \
+            /tmp/artifacts/test-k8s-state.new.json \
+            /tmp/artifacts/test-k8s-state.diff
           # Remove ANSI sequences
           sed -e 's/\x1b\[[0-9;]*m//g' -i /tmp/artifacts/test-k8s-state.diff || true
-
           # Prepare PR comment message
-          echo -e "  ##  # ${{ env.SERVICE_NAME }} Kubernetes Diff [CI]\n\n" >> /tmp/artifacts/test-k8s-state.diff.message
+          echo -e "### ${{ env.SERVICE_NAME }} Kubernetes Diff [CI]\n\n" >> /tmp/artifacts/test-k8s-state.diff.message
           echo -e "Between \`base\` ${{ github.event.pull_request.base.sha }} :arrow_left:  \`head\` ${{ github.event.pull_request.head.sha }}.\n\n" >> /tmp/artifacts/test-k8s-state.diff.message
           echo -e "<details>\n<summary>Expand</summary>\n\n\`\`\`diff\n" >> /tmp/artifacts/test-k8s-state.diff.message
-          head -c 50000 /tmp/artifacts/test-k8s-state.diff >> /tmp/artifacts/test-k8s-state.diff.message || true
+          head -c 50000 /tmp/artifacts/test-k8s-state.diff >> /tmp/artifacts/test-k8s-state.diff.message
           echo -e "\n\n(see artifacts in the Github Action for more information)\n\`\`\`\n</details>" >> /tmp/artifacts/test-k8s-state.diff.message
 
       - name: Dump logs
@@ -177,7 +233,6 @@ jobs:
           if-no-files-found: error
 
       - name: Send PR comment
-        if: always()
         uses: marocchino/sticky-pull-request-comment@v2
         with:
           header: "${{ env.KUBERNETES_NAMESPACE }}-kubernetes-state-diff"
